// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CreateDeviceReq struct {
	ProductId int    `json:"productId"`
	Name      string `json:"name"`
	Info      string `json:"info"`
}

type CreateDeviceResp struct {
	Info DeviceInfo `json:"info"`
}

type DeviceInfo struct {
	Id        int64  `json:"id"`
	ProductId int    `json:"productId"`
	Name      string `json:"name"`
	Info      string `json:"info"`
	Status    int    `json:"status"`
	IsOnline  int    `json:"isOnline"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type ListDeviceReq struct {
	Page int `form:"page,default=1"`
	Size int `form:"size,default=10"`
}

type ListDeviceResp struct {
	Total int64        `json:"total"`
	List  []DeviceInfo `json:"list"`
}
