// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CreateDeviceReq struct {
	ProductId  int    `json:"productId"`
	DeviceName string `json:"deviceName"`
	Info       string `json:"info,optional"`
}

type DeviceInfo struct {
	Id         int64  `json:"id"`
	ProductId  int    `json:"productId"`
	DeviceName string `json:"deviceName"`
	Info       string `json:"info"`
	Status     int    `json:"status"`
	IsOnline   int    `json:"isOnline"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}

type DeviceLoginReq struct {
	Username    string `json:"username"`                       //用户名
	Password    string `json:"password,optional"`              //密码
	Ip          string `json:"ip"`                             //访问的ip地址
	Certificate string `json:"certificate,optional,omitempty"` //客户端证书 base64后传过来
}

type DeviceLoginResp struct {
	Result string `json:"result"` //验证结果 "allow" | "deny" | "ignore"
}

type DeviceResp struct {
	Info DeviceInfo `json:"info"`
}

type ListDeviceReq struct {
	Page int `form:"page,default=1"`
	Size int `form:"size,default=10"`
}

type ListDeviceResp struct {
	Total int64        `json:"total"`
	List  []DeviceInfo `json:"list"`
}

type ProductDetailReq struct {
	Id int `form:"id"`
}

type ProductDetailResp struct {
	Info ProductInfo `json:"info"`
}

type ProductInfo struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}
