// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	device "api/internal/handler/device"
	deviceauth "api/internal/handler/device/auth"
	product "api/internal/handler/product"
	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: device.CreateDeviceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: device.ListDeviceHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/device"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 设备登录认证
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: deviceauth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/device/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: product.DetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/product"),
	)
}
